### ISSUE TITLE
timestamp values are not padded with zeros

### ISSUE THREAD

**Issue by 90-008** [Shiva-Shadowsong/loggie#11]
using latest loggie from the asset library, the timestamp don't seem to be padded with zeros. i verified it with hour / minute / second, not sure with dates. i fixed it locally and intent on making a PR but i wanted to make an issue first

**Comment by Shiva-Shadowsong** [comment]
You're right. 
I tested on 1.4 but it should be the same on earlier versions too since they're all using the `Time.get_datetime_dict_from_system` function which returns a dictionary where values are integers, therefore it's not going to do any padding automatically. 

Formatting the returned values without adding padding on our own simply returns `1.1.1970 0:0:0` (for unix timestamp `0` as an example).

I'll wait for your PR then. 👍

**Comment by Shiva-Shadowsong** [comment]
Update - I just checked again just in case, and no actually, this was a regression introduced in the last patch when I switch from using `Time.get_datetime_string_from_unix_time` to `Time.get_datetime_dict_from_system` to allow for formatting flexibility via the `LoggieSettings.format_timestamp` variable.
Please ensure your fix preserves compatibility with this feature.
