### ISSUE TITLE
Orphan nodes

### ISSUE THREAD

**Issue by pastque** [Shiva-Shadowsong/loggie#14]
Running the project with the plugin enabled found that there was always an orphan node, print_orphan_nodes() ->
![image](https://github.com/user-attachments/assets/429f30fc-ba7a-4bcf-bb94-5ce789a2b68e)
It turns out that "class_name LoggieSettings extends Node" was instantiated but not added to the tree, Upon checking that this LoggieSettings is only used for storage can be replaced with "class_name LoggieSettings extends RefCounted".

It is recommended that those that do not use node function should be replaced with "RefCounted".

**Comment by Shiva-Shadowsong** [comment]
Yes, there is definitely something going on with orphan nodes, I wrote about it in [this](https://github.com/users/Shiva-Shadowsong/projects/2?pane=issue&itemId=83082932) card in the Loggie project, and is most likely the outcome of the same issue you are reporting.

I will look into it over this weekend so that we can have this fixed in 1.5.
